# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelAPP.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 55, 16))
        self.label.setObjectName("label")
        self.Camera_Box = QtWidgets.QComboBox(self.centralwidget)
        self.Camera_Box.setGeometry(QtCore.QRect(50, 20, 141, 22))
        self.Camera_Box.setObjectName("Camera_Box")
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(200, 20, 93, 28))
        self.Start_Button.setObjectName("Start_Button")
        self.Stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_Button.setGeometry(QtCore.QRect(310, 20, 93, 28))
        self.Stop_Button.setObjectName("Stop_Button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 10, 81, 16))
        self.label_2.setObjectName("label_2")
        self.CPU_label = QtWidgets.QLabel(self.centralwidget)
        self.CPU_label.setGeometry(QtCore.QRect(480, 30, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CPU_label.setFont(font)
        self.CPU_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.CPU_label.setText("")
        self.CPU_label.setAlignment(QtCore.Qt.AlignCenter)
        self.CPU_label.setObjectName("CPU_label")
        self.RAM_label = QtWidgets.QLabel(self.centralwidget)
        self.RAM_label.setGeometry(QtCore.QRect(610, 30, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.RAM_label.setFont(font)
        self.RAM_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.RAM_label.setText("")
        self.RAM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RAM_label.setObjectName("RAM_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 10, 81, 16))
        self.label_3.setObjectName("label_3")
        self.Camera_label = QtWidgets.QLabel(self.centralwidget)
        self.Camera_label.setGeometry(QtCore.QRect(220, 130, 351, 301))
        self.Camera_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Camera_label.setText("")
        self.Camera_label.setObjectName("Camera_label")
        self.Predict_label = QtWidgets.QLabel(self.centralwidget)
        self.Predict_label.setGeometry(QtCore.QRect(300, 490, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.Predict_label.setFont(font)
        self.Predict_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Predict_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Predict_label.setText("")
        self.Predict_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Predict_label.setObjectName("Predict_label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 470, 100, 16))
        self.label_4.setObjectName("label_4")
        self.Predict_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Predict_Button.setGeometry(QtCore.QRect(190, 510, 93, 28))
        self.Predict_Button.setObjectName("Predict_Button")
        self.Model_Box = QtWidgets.QComboBox(self.centralwidget)
        self.Model_Box.setGeometry(QtCore.QRect(620, 460, 131, 22))
        self.Model_Box.setObjectName("Model_Box")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 430, 100, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Camera"))
        self.Start_Button.setText(_translate("MainWindow", "Start"))
        self.Stop_Button.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "CPU Usage"))
        self.label_3.setText(_translate("MainWindow", "RAM Usage"))
        self.label_4.setText(_translate("MainWindow", "Predict Label"))
        self.Predict_Button.setText(_translate("MainWindow", "Start Predict"))
        self.label_5.setText(_translate("MainWindow", "Choose Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
